backend:
  name: git-gateway
  branch: main

media_folder: "public/static/images"
public_folder: "/static/images"

collections:
  - name: "blog"
    label: "博客文章"
    folder: "data/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "草稿", name: "draft", widget: "boolean", default: false}
      - {label: "摘要", name: "summary", widget: "text"}
      - {label: "作者", name: "authors", widget: "list", default: ["default"]}
      - {label: "正文", name: "body", widget: "markdown"}
      
  - name: "authors"
    label: "作者"
    folder: "data/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "姓名", name: "name", widget: "string"}
      - {label: "头像", name: "avatar", widget: "image"}
      - {label: "职业", name: "occupation", widget: "string"}
      - {label: "公司", name: "company", widget: "string"}
      - {label: "邮箱", name: "email", widget: "string"}
      - {label: "简介", name: "body", widget: "markdown"}